name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 比如 v1.0.0
    branches:
      - master

permissions:
  contents: write  # 这一行非常关键！

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up GCC
      run: sudo apt-get install -y gcc

    - name: Build the project
      run: gcc -o hello test.c

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hello-ci
        path: hello

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: hello-ci

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Hello CI Release
        body: Automatic release of hello-ci
        prerelease: false
        draft: false
        files: hello
